/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vistas.Reparacion;

import Entidades.Bicicleta;
import Entidades.Cliente;
import Entidades.Repuesto;
import Entidades.Servicio;
import static TestUMLs.ProyectoFinalUniversidadG8.bd;
import static TestUMLs.ProyectoFinalUniversidadG8.cd;
import static TestUMLs.ProyectoFinalUniversidadG8.repud;
import static TestUMLs.ProyectoFinalUniversidadG8.sd;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tcnlu
 */
public class Reparacion_Agregar extends javax.swing.JPanel {

    /**
     * Creates new form Reparacion_Agregar
     */
    private final DefaultTableModel modelo;

    public Reparacion_Agregar() {
        initComponents();
        this.modelo = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        armarCabeceraTabla();
        actualizarListaBicis();
        actualizarListaRepuestos();
        actualizarListaServicios();
        JTFNombreCompleto.setEnabled(false);
        JTFCostoTotalAgregarReparacion.setEnabled(false);
        JTFCostoServicioAgregarReparacion.setEnabled(false);
        JTFDNI.setEnabled(false);
        JTFTelefono.setEnabled(false);
        JTItemRepuestoAgregarReparacion.getTableHeader().setReorderingAllowed(false);
    }

    private void actualizarListaBicis() {
        JCBBicicletasAgregarReparacion.removeAllItems();
        for (Bicicleta lista : bd.obtenerBicicletas()) {
            JCBBicicletasAgregarReparacion.addItem(lista.getTipo() + " " + lista.getColor() + " " + lista.getNumSerie());
        }
    }

    private void actualizarListaServicios() {
        JCBServiciosAgregarReparacion.removeAllItems();
        for (Servicio lista : sd.obtenerServicios()) {
            JCBServiciosAgregarReparacion.addItem(lista.getDescripcion());
        }
    }

    private void actualizarListaRepuestos() {
        JCBRepuestosAgregarReparacion.removeAllItems();
        for (Repuesto lista : repud.obtenerRepuestos()) {
            JCBRepuestosAgregarReparacion.addItem(lista.getDescripcion());
        }
    }

    private void armarCabeceraTabla() {
        ArrayList<Object> columnas = new ArrayList<>();
        columnas.add("N°Serie");
        columnas.add("Descripción");
        columnas.add("Costo u.");
        columnas.add("Cantidad");
        for (Object it : columnas) {
            modelo.addColumn(it);
        }
        JTItemRepuestoAgregarReparacion.setModel(modelo);
    }

    private void borrarFilasTabla() {
        if (modelo != null) {
            int a = modelo.getRowCount() - 1;
            for (int i = a; i >= 0; i--) {
                modelo.removeRow(i);
            }
        }
    }

    private void cargarItem(Repuesto r, int cant) {
        modelo.addRow(new Object[]{r.getNumSerie(), r.getDescripcion(), r.getPrecio(), cant});
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        JCBBicicletasAgregarReparacion = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        JTFTelefono = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        JTFDNI = new javax.swing.JTextField();
        JTFNombreCompleto = new javax.swing.JTextField();
        JCBServiciosAgregarReparacion = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        JCBRepuestosAgregarReparacion = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        JTFCantRepuestoAgregarReparacion = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        JBGuardarAgregarReparacion = new java.awt.Button();
        JBAgregarRepuestoAgregarReparacion = new java.awt.Button();
        JBLimpiarAgregarReparacion = new java.awt.Button();
        jLabel12 = new javax.swing.JLabel();
        JTFCostoTotalAgregarReparacion = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTItemRepuestoAgregarReparacion = new javax.swing.JTable();
        JTFCostoServicioAgregarReparacion = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        JBCalcularCostoAgregarReparacion = new java.awt.Button();

        setMaximumSize(new java.awt.Dimension(398, 600));
        setMinimumSize(new java.awt.Dimension(398, 600));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(398, 600));

        jLabel2.setFont(new java.awt.Font("Yu Gothic Medium", 0, 24)); // NOI18N
        jLabel2.setText("Nueva Reparacion");

        jLabel8.setFont(new java.awt.Font("Yu Gothic Medium", 0, 18)); // NOI18N
        jLabel8.setText("Bicicletas");

        JCBBicicletasAgregarReparacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        JCBBicicletasAgregarReparacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCBBicicletasAgregarReparacionActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        jLabel9.setText("Datos dueño");

        jLabel3.setText("DNI :");

        jLabel4.setText("Nombre :");

        jLabel5.setText("Telefono :");

        JTFDNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFDNIActionPerformed(evt);
            }
        });

        JTFNombreCompleto.setEnabled(false);
        JTFNombreCompleto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFNombreCompletoActionPerformed(evt);
            }
        });

        JCBServiciosAgregarReparacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        JCBServiciosAgregarReparacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCBServiciosAgregarReparacionActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Yu Gothic Medium", 0, 18)); // NOI18N
        jLabel10.setText("Servicios");

        JCBRepuestosAgregarReparacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        JCBRepuestosAgregarReparacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCBRepuestosAgregarReparacionActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Yu Gothic Medium", 0, 18)); // NOI18N
        jLabel11.setText("Repuestos");

        jLabel6.setText("Cant:");

        JBGuardarAgregarReparacion.setActionCommand("Guardar");
        JBGuardarAgregarReparacion.setLabel("Guardar");
        JBGuardarAgregarReparacion.setName(""); // NOI18N
        JBGuardarAgregarReparacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBGuardarAgregarReparacionActionPerformed(evt);
            }
        });

        JBAgregarRepuestoAgregarReparacion.setActionCommand("AgregarRepuesto");
        JBAgregarRepuestoAgregarReparacion.setLabel("Agregar");
        JBAgregarRepuestoAgregarReparacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBAgregarRepuestoAgregarReparacionActionPerformed(evt);
            }
        });

        JBLimpiarAgregarReparacion.setLabel("Limpiar");
        JBLimpiarAgregarReparacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBLimpiarAgregarReparacionActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        jLabel12.setText("Costo Total: ");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("ItemRepuesto"));

        JTItemRepuestoAgregarReparacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        JTItemRepuestoAgregarReparacion.setEnabled(false);
        jScrollPane1.setViewportView(JTItemRepuestoAgregarReparacion);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
        );

        jLabel7.setText("Costo:");

        JBCalcularCostoAgregarReparacion.setActionCommand("Calcular");
        JBCalcularCostoAgregarReparacion.setLabel("Calcular");
        JBCalcularCostoAgregarReparacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBCalcularCostoAgregarReparacionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(JTFTelefono)
                            .addComponent(JTFNombreCompleto)
                            .addComponent(JTFDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(JCBServiciosAgregarReparacion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(JTFCostoTotalAgregarReparacion))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(JCBRepuestosAgregarReparacion, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(6, 6, 6)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(JTFCantRepuestoAgregarReparacion, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JBAgregarRepuestoAgregarReparacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addComponent(JTFCostoServicioAgregarReparacion))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(JBLimpiarAgregarReparacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JBGuardarAgregarReparacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel9)
                            .addComponent(JCBBicicletasAgregarReparacion, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JBCalcularCostoAgregarReparacion, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JCBBicicletasAgregarReparacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(JTFDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(JTFNombreCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(JTFTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JCBServiciosAgregarReparacion))
                    .addComponent(JTFCostoServicioAgregarReparacion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(JCBRepuestosAgregarReparacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(JTFCantRepuestoAgregarReparacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6))
                    .addComponent(JBAgregarRepuestoAgregarReparacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(5, 5, 5)
                .addComponent(JBCalcularCostoAgregarReparacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JBGuardarAgregarReparacion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12)
                        .addComponent(JTFCostoTotalAgregarReparacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(JBLimpiarAgregarReparacion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void JCBBicicletasAgregarReparacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCBBicicletasAgregarReparacionActionPerformed
        if (JCBBicicletasAgregarReparacion.getSelectedIndex() >= 0) {
            JCBBicicletasAgregarReparacion.setSelectedIndex(JCBBicicletasAgregarReparacion.getSelectedIndex());
            JTFNombreCompleto.setText(bd.obtenerBicicletas().get(JCBBicicletasAgregarReparacion.getSelectedIndex()).getDueño().getNombre() + " " + bd.obtenerBicicletas().get(JCBBicicletasAgregarReparacion.getSelectedIndex()).getDueño().getApellido());
            JTFTelefono.setText(String.valueOf(bd.obtenerBicicletas().get(JCBBicicletasAgregarReparacion.getSelectedIndex()).getDueño().getTelefono()));
            JTFDNI.setText(String.valueOf(bd.obtenerBicicletas().get(JCBBicicletasAgregarReparacion.getSelectedIndex()).getDueño().getDni()));
        }
    }//GEN-LAST:event_JCBBicicletasAgregarReparacionActionPerformed

    private void JTFDNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFDNIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFDNIActionPerformed

    private void JTFNombreCompletoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFNombreCompletoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFNombreCompletoActionPerformed

    private void JCBServiciosAgregarReparacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCBServiciosAgregarReparacionActionPerformed
        if (JCBServiciosAgregarReparacion.getSelectedIndex() >= 0) {
            JCBServiciosAgregarReparacion.setSelectedIndex(JCBServiciosAgregarReparacion.getSelectedIndex());
            JTFCostoServicioAgregarReparacion.setText(String.valueOf(sd.obtenerServicios().get(JCBServiciosAgregarReparacion.getSelectedIndex()).getPrecio()));
        }
    }//GEN-LAST:event_JCBServiciosAgregarReparacionActionPerformed

    private void JCBRepuestosAgregarReparacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCBRepuestosAgregarReparacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JCBRepuestosAgregarReparacionActionPerformed

    private void JBGuardarAgregarReparacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBGuardarAgregarReparacionActionPerformed
        /* try {
            cd.borrarCliente(Integer.parseInt(JTFDNI.getText()));
            JBLimpiarBorrarClienteActionPerformed(evt);
            actualizarLista();
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Error eliminando el cliente.");
        }*/
    }//GEN-LAST:event_JBGuardarAgregarReparacionActionPerformed

    private void JBAgregarRepuestoAgregarReparacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBAgregarRepuestoAgregarReparacionActionPerformed
        Repuesto r = new Repuesto();
        try {

            if (JCBRepuestosAgregarReparacion.getSelectedIndex() >= 0) {
                JCBRepuestosAgregarReparacion.setSelectedIndex(JCBRepuestosAgregarReparacion.getSelectedIndex());
                r.setNumSerie(repud.obtenerRepuestos().get(JCBRepuestosAgregarReparacion.getSelectedIndex()).getNumSerie());
                r.setDescripcion(repud.obtenerRepuestos().get(JCBRepuestosAgregarReparacion.getSelectedIndex()).getDescripcion());
                r.setPrecio(repud.obtenerRepuestos().get(JCBRepuestosAgregarReparacion.getSelectedIndex()).getPrecio());
                r.setActivo(true);
            }
            cargarItem(r, Integer.valueOf(JTFCantRepuestoAgregarReparacion.getText()));
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Ingrese un n° valido de cantidad para repuesto.");
        }
    }//GEN-LAST:event_JBAgregarRepuestoAgregarReparacionActionPerformed

    private void JBLimpiarAgregarReparacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBLimpiarAgregarReparacionActionPerformed
        JCBRepuestosAgregarReparacion.setSelectedIndex(0);
        JCBServiciosAgregarReparacion.setSelectedIndex(0);
        JCBBicicletasAgregarReparacion.setSelectedIndex(0);
        borrarFilasTabla();
        JTFCostoTotalAgregarReparacion.setText("");
        JTFCantRepuestoAgregarReparacion.setText("");
    }//GEN-LAST:event_JBLimpiarAgregarReparacionActionPerformed

    private void JBCalcularCostoAgregarReparacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBCalcularCostoAgregarReparacionActionPerformed

        float suma = 0;
        suma += Float.valueOf(JTFCostoServicioAgregarReparacion.getText());

        for (int i = 0; i < JTItemRepuestoAgregarReparacion.getRowCount(); i++) {
            suma += Float.valueOf(JTItemRepuestoAgregarReparacion.getValueAt(i, 2).toString()) * Float.valueOf(JTItemRepuestoAgregarReparacion.getValueAt(i, 3).toString());
        }
        suma += suma * 0.1;
        JTFCostoTotalAgregarReparacion.setText(String.valueOf(suma));
    }//GEN-LAST:event_JBCalcularCostoAgregarReparacionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button JBAgregarRepuestoAgregarReparacion;
    private java.awt.Button JBCalcularCostoAgregarReparacion;
    private java.awt.Button JBGuardarAgregarReparacion;
    private java.awt.Button JBLimpiarAgregarReparacion;
    private javax.swing.JComboBox<String> JCBBicicletasAgregarReparacion;
    private javax.swing.JComboBox<String> JCBRepuestosAgregarReparacion;
    private javax.swing.JComboBox<String> JCBServiciosAgregarReparacion;
    private javax.swing.JTextField JTFCantRepuestoAgregarReparacion;
    private javax.swing.JTextField JTFCostoServicioAgregarReparacion;
    private javax.swing.JTextField JTFCostoTotalAgregarReparacion;
    private javax.swing.JTextField JTFDNI;
    private javax.swing.JTextField JTFNombreCompleto;
    private javax.swing.JTextField JTFTelefono;
    private javax.swing.JTable JTItemRepuestoAgregarReparacion;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
