/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vistas.Reparacion;

import Entidades.Reparacion;
import static TestUMLs.ProyectoFinalUniversidadG8.bd;
import static TestUMLs.ProyectoFinalUniversidadG8.repad;
import static TestUMLs.ProyectoFinalUniversidadG8.sd;
import java.time.LocalDate;
import java.time.format.DateTimeParseException;
import javax.swing.JOptionPane;

/**
 *
 * @author Santi
 */
public class Reparacion_Actualizar extends javax.swing.JPanel {

    /**
     * Creates new form Cliente_Actualizar
     */
    public Reparacion_Actualizar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        JBLimpiarActualizarReparacion = new java.awt.Button();
        JTFID = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        JBActualizarActualizarReparacion = new java.awt.Button();
        JBBuscarActualizarReparacion = new java.awt.Button();
        jLabel10 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        JTFFecha = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        JTFServicio = new javax.swing.JTextField();
        JTFIDBicicleta = new javax.swing.JTextField();
        JTFEstado = new javax.swing.JTextField();
        JTFCosto = new javax.swing.JTextField();

        setMaximumSize(new java.awt.Dimension(398, 600));
        setMinimumSize(new java.awt.Dimension(398, 600));
        setPreferredSize(new java.awt.Dimension(398, 600));

        jLabel3.setText("ID:");

        JBLimpiarActualizarReparacion.setLabel("Limpiar");
        JBLimpiarActualizarReparacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBLimpiarActualizarReparacionActionPerformed(evt);
            }
        });

        JTFID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFIDActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Yu Gothic Medium", 0, 24)); // NOI18N
        jLabel1.setText("Actualizar Reparacion");

        JBActualizarActualizarReparacion.setActionCommand("Actualizar");
        JBActualizarActualizarReparacion.setLabel("Actualizar");
        JBActualizarActualizarReparacion.setName(""); // NOI18N
        JBActualizarActualizarReparacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBActualizarActualizarReparacionActionPerformed(evt);
            }
        });

        JBBuscarActualizarReparacion.setActionCommand("Buscar");
        JBBuscarActualizarReparacion.setLabel("Buscar");
        JBBuscarActualizarReparacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBBuscarActualizarReparacionActionPerformed(evt);
            }
        });

        jLabel10.setText("Fecha:");

        jLabel4.setText("ID Bicicleta:");

        JTFFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFFechaActionPerformed(evt);
            }
        });

        jLabel7.setText("Estado:");

        jLabel5.setText("ID Servicio:");

        jLabel6.setText("Costo :");

        JTFIDBicicleta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFIDBicicletaActionPerformed(evt);
            }
        });

        JTFEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFEstadoActionPerformed(evt);
            }
        });

        JTFCosto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFCostoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4))
                                .addComponent(jLabel6))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel10))
                                .addGap(7, 7, 7)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JTFEstado)
                            .addComponent(JTFFecha)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(JTFIDBicicleta)
                                .addComponent(JTFServicio)
                                .addComponent(JTFCosto, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(JBBuscarActualizarReparacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JBLimpiarActualizarReparacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JBActualizarActualizarReparacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(JTFID, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(JTFID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(JBBuscarActualizarReparacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTFIDBicicleta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTFServicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTFCosto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JTFEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JTFFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)))
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 242, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JBActualizarActualizarReparacion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBLimpiarActualizarReparacion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void JBLimpiarActualizarReparacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBLimpiarActualizarReparacionActionPerformed
        JTFIDBicicleta.setText("");
        JTFServicio.setText("");
        JTFID.setText("");
        JTFEstado.setText("");
        JTFCosto.setText("");
        JTFFecha.setText("");
    }//GEN-LAST:event_JBLimpiarActualizarReparacionActionPerformed

    private void JTFIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFIDActionPerformed

    private void JBActualizarActualizarReparacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBActualizarActualizarReparacionActionPerformed
        if (JTFIDBicicleta.getText().isEmpty() || JTFServicio.getText().isEmpty() || JTFID.getText().isEmpty() || JTFEstado.getText().isEmpty() || JTFCosto.getText().isEmpty() || JTFFecha.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Llene todos los campos por favor");
        } else {
            try {
                Reparacion aux = repad.obtenerReparacionPorId(Integer.valueOf(JTFID.getText()));

                aux.setBicicleta(bd.obtenerBicicletaPorId(Integer.valueOf(JTFIDBicicleta.getText())));

                aux.setServicio(sd.obtenerServicioPorId(Integer.valueOf(JTFServicio.getText())));

                aux.setCostoFinal(Float.valueOf(JTFCosto.getText()));

                aux.setFechaEntrada(LocalDate.parse(JTFFecha.getText()));

                aux.setEstado(Boolean.valueOf(JTFEstado.getText()));
                System.out.println(aux);
                repad.actualizarReparacion(aux, Integer.valueOf(JTFID.getText()));
                JBLimpiarActualizarReparacionActionPerformed(evt);
            } catch (NumberFormatException | DateTimeParseException ex) {
                JOptionPane.showMessageDialog(null, "Error, verifique haber ingresado todos los datos correctamente.\n Por favor, respete el formato de fechas dispuesto por el programa, así como el estado (true/false)");
            }
        }
    }//GEN-LAST:event_JBActualizarActualizarReparacionActionPerformed

    private void JBBuscarActualizarReparacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBBuscarActualizarReparacionActionPerformed
        if (JTFID.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ingrese un N° ID por favor");
        } else {
            try {
                Reparacion aux = repad.obtenerReparacionPorId(Integer.parseInt(JTFID.getText()));
                JTFServicio.setText(String.valueOf(aux.getServicio().getCodigo()));
                JTFIDBicicleta.setText(String.valueOf(aux.getBicicleta().getNumSerie()));
                JTFFecha.setText(String.valueOf(aux.getFechaEntrada()));
                JTFCosto.setText(String.valueOf(aux.getCostoFinal()));
                JTFEstado.setText(String.valueOf(aux.isEstado()));
            } catch (NumberFormatException | NullPointerException ex) {
                JOptionPane.showMessageDialog(null, "ID invalido o inexistente.");
            }
        }
    }//GEN-LAST:event_JBBuscarActualizarReparacionActionPerformed

    private void JTFFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFFechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFFechaActionPerformed

    private void JTFIDBicicletaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFIDBicicletaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFIDBicicletaActionPerformed

    private void JTFEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFEstadoActionPerformed

    private void JTFCostoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFCostoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFCostoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button JBActualizarActualizarReparacion;
    private java.awt.Button JBBuscarActualizarReparacion;
    private java.awt.Button JBLimpiarActualizarReparacion;
    private javax.swing.JTextField JTFCosto;
    private javax.swing.JTextField JTFEstado;
    private javax.swing.JTextField JTFFecha;
    private javax.swing.JTextField JTFID;
    private javax.swing.JTextField JTFIDBicicleta;
    private javax.swing.JTextField JTFServicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
